apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-radar.name" . }}-backend
  labels:
    {{- include "crypto-radar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "crypto-radar.name" . }}-backend
